### ISSUE TITLE
Blog Post: sl0-m0 - Needs video added 

### ISSUE THREAD

**Issue by mhahn23** [pixelbakery/pb-oct-2022#105]

**Comment by mhahn23** [comment]
This video doesn't exist anymore when I try to play it. The whole article is just the video, should I delete the whole blog? @jordanlambrecht

**Comment by jordanlambrecht** [comment]
Yup fuck it

Jordan D Lambrecht
Director + Founder
c: 402 413 8366
o: 402 302 0323
Pixel Bakery Design Studio
pixelbakery.com

**Comment by mhahn23** [comment]
Resolves #105
