### ISSUE TITLE
Page Header – Call-out Copy

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#114]
Created by Jordan Lambrecht via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
@jordanlambrecht 

Our success is a direct result of the people that we meet, whether that be our employees, our clients, or community members. As such, we believe in giving back to our community through education. We are proponents of breaking down any barriers (e.g. monetary costs) that prevent creativity and believe that everyone should have access to high-quality educational experiences and resources.

**Comment by jordanlambrecht** [comment]
too long
