### ISSUE TITLE
Project Files – Body Copy

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#115]
Created by Jordan Lambrecht via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
@jordanlambrecht Kind of hate this copy but idk:

Expanding educational opportunities is more possible now than ever before with advancements in technology. PB believes open-sourcing our files is one of countless ways we can break down legal, financial, or technical barriers that prevent creativity and believe that everyone should have access to high-quality educational experiences and resources.
