### ISSUE TITLE
"Become A Client" – Body Copy

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#124]
Created by Jordan Lambrecht via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
@jordanlambrecht Feel free to mend and make more humorous as you see fit:

Schedule a meeting with our leadership team to discuss your next big project and to see if we’re a good fit for one another! We like to think of discovery meetings as speed dating: seeing if our goals and missions align and making sure there’s enough chemistry there for something long-lasting to evolve. We believe in building long-term relationships with our clients, so making sure all of these pieces are in check is of utmost importance.
