### ISSUE TITLE
"Work We're Proud Of" – Body Copy

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#125]
Created by Jordan Lambrecht via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
@jordanlambrecht I'm still unhappy with this so feel free to edit/add the PB flair:

Everything we put out into the world is a unique piece of its own and wouldn’t exist without the approval of each and every person involved in its creation. However, there are a few pieces that we’re really, really, really proud of. Here are a few of our favorites.
