### ISSUE TITLE
"Our Lovely Clients" – Body Copy

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#126]
Created by Jordan Lambrecht via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
Our story wouldn’t exist if it weren’t for all of the wonderful clients that have been on this journey with us. From initial discovery meetings to seeing the final product, we thrive in bringing a client’s vision to life. Check out some of our past and present clients below.

@jordanlambrecht
