### ISSUE TITLE
Start Something Wonderful: newsletter checkbox unaligned with text. also, the CTA looks off and might work better centered

### ISSUE THREAD

**Issue by oliviaboldt** [pixelbakery/pb-oct-2022#149]
![Screen Shot 2022-02-22 at 3 25 20 PM](https://user-images.githubusercontent.com/94932415/155222221-8916f683-1e7b-4934-9bfa-159a873e68e0.png)

@jordanlambrecht

**Comment by jordanlambrecht** [comment]
Fixed in a previous commit
