### ISSUE TITLE
Body – Animation & Motion Design

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#161]
Created by Olivia Boldt via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
We specialize in 2D and 3D animation, motion graphics, stop motion, and 3D modeling. Every animation project is full-service and includes project management, creative concepting, sound design, storyboarding, and voiceover as needed. Whether you’re looking for a lower thirds animation template or a sizzle reel of your company’s coolest products, we’ve got you covered. Check out what else we have to offer below.

@jordanlambrecht
