### ISSUE TITLE
Body – Emerging Media

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#169]
Created by Olivia Boldt via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
With the development and expansion of social media, mobile marketing, email marketing, instant messaging, and various other digital platforms, it only makes sense that current trends in marketing are ever-evolving. Why not evolve with them?

Here at PB, we like to stay up-to-date with the newest techniques and strategies that share information in innovative, interactive ways. Emerging media allows you and your brand to speak closer to your customers than ever before.

@jordanlambrecht oof feel free to edit and add exactly what services this would entail
