### ISSUE TITLE
Description – Kinetic Typography

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#185]
Created by Olivia Boldt via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
Kinetic typography is an animation technique used to make text move in numerous ways – whether that be expanding, shrinking, or moving in slow-motion, to name a few. The effect adds emphasis to the text’s meaning, or can simply add an element of motion to your videos.

@jordanlambrecht

**Comment by oliviaboldt** [comment]
I hate this reading it back. Don't want to sound all mansplain-y over here.
