### ISSUE TITLE
Description – Product Sizzles

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#186]
Created by Olivia Boldt via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
@jordanlambrecht 

An animated sizzle reel is a short (three minutes or less) promotional video that highlights a specific product or service. This is edited with short animation, graphics, and text clips. Tied together with a groovy soundtrack leaves your audience wanting to see more of your brand.
